name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start SSH Agent
        run: |
          eval "$(ssh-agent -s)"
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh-add -

      - name: Set up Docker BuildKit
        run: export DOCKER_BUILDKIT=1

      - name: Build and push Docker image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build --ssh default -t evans8109/tir102-prefect:latest .
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
          docker push evans8109/tir102-prefect:latest